In [1]:
# ML에서는 결손값(NaN, Null)이 허용되지 않음. 
# 따라서 이러한 결손값은  고정된 다른 값으로 변환하거나(피처의 평균값 등)해당 피처 드롭
# Scikit learn의 ML 알고리즘은 문자열 값을 Input으로 허용하지 않음
# 따라서 모든 문자열 값은 인코딩돼서 숫자형으로 변환해야함
# 문자열 피처는 카테고리형 피처와 텍스트형 피처를 의미함
# 대표적인 인코딩 방식으로는 레이블 인코딩과 원-핫 인코딩이 있음
# 레이블 인코딩 : 카테고리 피처를 코드형 숫자 값으로 변환

In [2]:
from sklearn.preprocessing import LabelEncoder

items=['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']

#LabelEncoder를 객체로 생성한 후, fit와 transform으로 레이블 인코딩
encoder =LabelEncoder()
encoder.fit(items)
labels=encoder.transform(items)
print('인코딩 변환값:', labels)
print('인코딩 클래스:',encoder.classes_)
print('디코딩 원본값:',encoder.inverse_transform([4,5,2,0,1,1,3,3]))

인코딩 변환값: [0 1 4 5 3 3 2 2]
인코딩 클래스: ['TV' '냉장고' '믹서' '선풍기' '전자레인지' '컴퓨터']
디코딩 원본값: ['전자레인지' '컴퓨터' '믹서' 'TV' '냉장고' '냉장고' '선풍기' '선풍기']


In [3]:
# 레이블 인코딩은 일괄적인 숫자 값으로 변환시키기 때문에, 몇몇 ML 알고리즘에선 예측 성능이 떨어짐
# 숫자 값의 크고 작음에 대한 특성이 작용하기 때문임
# 숫자값이 더 큰 것에대해 ML알고리즘이 가중치를 더 부여한다거나 더 중요하다고 인식 하는 등과 같이.
# 그래서 선형회귀와 같은 ML알고리즘에선 사용하지 않고, 트리 계열의 ML알고리즘에서 사용

In [4]:
# 원-핫 인코딩 : 피처 값의 유형에 따라 새로운 피처를 추가해 고유 값에 해당하는 칼럼에만 1을 표시. 그외 칼럼에는 0을 표시
# 행 형태로 돼 있는 피처의 고유 값 → 열 형태로 변환 후, 고유 값에 해당하는 칼럼에만 1을 표시, 나머지 칼럼엔 0을 표시
# OneHotEncoder 클래스의 입력값은 2차원 데이터이며, 반환값은 희소 행렬이므로 toarray를 활용하여 밀집 행렬로 바꿔줘야 함
from sklearn.preprocessing import OneHotEncoder
import numpy as np

items=['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']

#2차원으로 변환
items = np.array(items).reshape(-1,1)

#원-핫 인코딩
oh_encoder=OneHotEncoder()
oh_encoder.fit(items)
oh_labels = oh_encoder.transform(items)

#toarrary를 활용하여 밀집 행렬로 변환
print('원-핫 인코딩 데이터')
print(oh_labels.toarray())
print('원-핫 인코딩 데이터 차원')
print(oh_labels.shape)

원-핫 인코딩 데이터
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
원-핫 인코딩 데이터 차원
(8, 6)


In [5]:
import pandas as pd

df=pd.DataFrame({'items':['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']})
pd.get_dummies(df)

items_TV  items_냉장고  items_믹서  items_선풍기  items_전자레인지  items_컴퓨터
0         1          0         0          0            0          0
1         0          1         0          0            0          0
2         0          0         0          0            1          0
3         0          0         0          0            0          1
4         0          0         0          1            0          0
5         0          0         0          1            0          0
6         0          0         1          0            0          0
7         0          0         1          0            0          0

In [6]:
# 피처 스케일링(Feature Scaling) : 서로 다른 변수의 값 범위를 일정한 수준으로 맞추는 작업
# ㄴ 표준화 : 가우시안 정규 분포(평균 0, 분산 1)를 가진 값을 변환
#             사이킷런에서 구현한 RBF 커널을 이용하는 서포트 벡터 머신, 선형 회귀, 로지스틱 회귀의 경우 데이터가 가우시안 분포를
#             가지고 있다고 가정하고 구현됐기 때문에, 사전에 표준화를 적용하는 것은 예측 성능 향상에 중요한 요소가 될 수 있음
# ㄴ 정규화 :  다른 피처의 크기를 통일

In [8]:
from sklearn.datasets import load_iris

iris=load_iris()
iris_data=iris.data
iris_df=pd.DataFrame(data=iris_data, columns=iris.feature_names)

print('feature들의 평균')
print(iris_df.mean())
print('feature들의 분산')
print(iris_df.var())

feature들의 평균
sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64
feature들의 분산
sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64


In [9]:
from sklearn.preprocessing import StandardScaler

scaler=StandardScaler()
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

#transform시 스케일 변환된 데이터 세트가 Numpy ndarray로 반한돼 이를 DataFrame으로 변환
iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)
print('feature들의 평균:')
print(iris_df_scaled.mean())
print('feature들의 분산:')
print(iris_df_scaled.var())

feature들의 평균:
sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64
feature들의 분산:
sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64


In [10]:
# MinMaxScaler : 데이터값을 0과 1사이의 범위 값으로 변환(음수의 경우 -1에서 1값으로 변환)
#                데이터의 분포가 가우시안 분포가 아닐 경우 사용
from sklearn.preprocessing import MinMaxScaler

scaler=MinMaxScaler()
scaler.fit(iris_df)
iris_scaled=scaler.transform(iris_df)

#transform시 스케일 변환된 데이터 세트가 Numpy ndarray로 반한돼 이를 DataFrame으로 변환
iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)
print('feature들의 최솟값')
print(iris_df_scaled.min())
print('feature들의 최댓값')
print(iris_df_scaled.max())

feature들의 최솟값
sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64
feature들의 최댓값
sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64


In [12]:
# 학습데이터 0부터 10까지, 테스트 데이터는 0부터 5까지 
train_array=np.arange(0,11).reshape(-1,1)
test_array=np.arange(0,6).reshape(-1,1)

# MinMaxScaler 객체에 별도의 feature_range 파라미터 값을 지정하지 않으면 0~1값으로 변환
scaler=MinMaxScaler()

# fit하게 되면 train_array 데이터의 최솟값이 0, 최댓값이 10으로 설정
scaler.fit(train_array)

# 1/10 스케일로 train_array 변환
train_scaled=scaler.transform(train_array)

print('원본 train_array: ', np.round(train_array.reshape(-1), 2))
print('Scale된 train_array: ', np.round(train_scaled.reshape(-1), 2))

원본 train_array:  [ 0  1  2  3  4  5  6  7  8  9 10]
Scale된 train_array:  [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [13]:
# fit하게 되면 test_array 데이터의 최솟값이 0, 최댓값이 5으로 설정
scaler.fit(test_array)

# 1/5 스케일로 test_array 변환
test_scaled=scaler.transform(test_array)

print('원본 test_array: ', np.round(test_array.reshape(-1), 2))
print('Scale된 test_array: ', np.round(test_scaled.reshape(-1), 2))

원본 test_array:  [0 1 2 3 4 5]
Scale된 test_array:  [0.  0.2 0.4 0.6 0.8 1. ]


In [14]:
# ↑학습 데이터와 테스트 데이터의 서로 다른 원본값이 동일한 값으로 변환
scaler=MinMaxScaler()
scaler.fit(train_array)
train_scaled=scaler.transform(train_array)
print('원본 train_array: ', np.round(train_array.reshape(-1), 2))
print('Scale된 train_array: ', np.round(train_scaled.reshape(-1), 2))

# test_array에 Scale 변환을 할 때에는 반드시 fit을 호출하지 않고, transform만!
test_scaled = scaler.transform(test_array)
print('\n원본 test_array 데이터: ', np.round(test_array.reshape(-1),2))
print('Scale된 test_array: ', np.round(test_scaled.reshape(-1), 2))

원본 train_array:  [ 0  1  2  3  4  5  6  7  8  9 10]
Scale된 train_array:  [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]

원본 test_array 데이터:  [0 1 2 3 4 5]
Scale된 test_array:  [0.  0.1 0.2 0.3 0.4 0.5]


In [ ]:
# 가능하다면 전체 데이터의 스케일링 변환을 적용한 뒤 학습과 테스트 데이터로 분리
# 위와 같이 할 수 없다면, 테스트 데이터 변환 시에는 fit나 fit_transform을 사용하지않고, 학습 데이터로 이미 fit된 Scaler 객체를
# 이용하여 transform으로 변환