In [1]:
# ML에서는 결손값(NaN, Null)이 허용되지 않음. 
# 따라서 이러한 결손값은  고정된 다른 값으로 변환하거나(피처의 평균값 등)해당 피처 드롭
# Scikit learn의 ML 알고리즘은 문자열 값을 Input으로 허용하지 않음
# 따라서 모든 문자열 값은 인코딩돼서 숫자형으로 변환해야함
# 문자열 피처는 카테고리형 피처와 텍스트형 피처를 의미함
# 대표적인 인코딩 방식으로는 레이블 인코딩과 원-핫 인코딩이 있음
# 레이블 인코딩 : 카테고리 피처를 코드형 숫자 값으로 변환

In [4]:
from sklearn.preprocessing import LabelEncoder

items=['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']

#LabelEncoder를 객체로 생성한 후, fit와 transform으로 레이블 인코딩
encoder =LabelEncoder()
encoder.fit(items)
labels=encoder.transform(items)
print('인코딩 변환값:', labels)
print('인코딩 클래스:',encoder.classes_)
print('디코딩 원본값:',encoder.inverse_transform([4,5,2,0,1,1,3,3]))

인코딩 변환값: [0 1 4 5 3 3 2 2]
인코딩 클래스: ['TV' '냉장고' '믹서' '선풍기' '전자레인지' '컴퓨터']
디코딩 원본값: ['전자레인지' '컴퓨터' '믹서' 'TV' '냉장고' '냉장고' '선풍기' '선풍기']


In [5]:
# 레이블 인코딩은 일괄적인 숫자 값으로 변환시키기 때문에, 몇몇 ML 알고리즘에선 예측 성능이 떨어짐
# 숫자 값의 크고 작음에 대한 특성이 작용하기 때문임
# 숫자값이 더 큰 것에대해 ML알고리즘이 가중치를 더 부여한다거나 더 중요하다고 인식 하는 등과 같이.
# 그래서 선형회귀와 같은 ML알고리즘에선 사용하지 않고, 트리 계열의 ML알고리즘에서 사용

In [7]:
# 원-핫 인코딩 : 피처 값의 유형에 따라 새로운 피처를 추가해 고유 값에 해당하는 칼럼에만 1을 표시. 그외 칼럼에는 0을 표시
# 행 형태로 돼 있는 피처의 고유 값 → 열 형태로 변환 후, 고유 값에 해당하는 칼럼에만 1을 표시, 나머지 칼럼엔 0을 표시
# OneHotEncoder 클래스의 입력값은 2차원 데이터이며, 반환값은 희소 행렬이므로 toarray를 활용하여 밀집 행렬로 바꿔줘야 함
from sklearn.preprocessing import OneHotEncoder
import numpy as np

items=['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']

#2차원으로 변환
items = np.array(items).reshape(-1,1)

#원-핫 인코딩
oh_encoder=OneHotEncoder()
oh_encoder.fit(items)
oh_labels = oh_encoder.transform(items)

#toarrary를 활용하여 밀집 행렬로 변환
print('원-핫 인코딩 데이터')
print(oh_labels.toarray())
print('원-핫 인코딩 데이터 차원')
print(oh_labels.shape)

원-핫 인코딩 데이터
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
원-핫 인코딩 데이터 차원
(8, 6)


In [8]:
import pandas as pd

df=pd.DataFrame({'items':['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']})
pd.get_dummies(df)

items_TV  items_냉장고  items_믹서  items_선풍기  items_전자레인지  items_컴퓨터
0         1          0         0          0            0          0
1         0          1         0          0            0          0
2         0          0         0          0            1          0
3         0          0         0          0            0          1
4         0          0         0          1            0          0
5         0          0         0          1            0          0
6         0          0         1          0            0          0
7         0          0         1          0            0          0